name: Latest Techblogposts post workflow
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '/api/parse-rss' \
          --header 'Authorization: Bearer ${{ process.env.API_KEY }}'
