name: Latest Techblogposts post workflow
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://techblogposts.com/api/parse-rss' \
